`ifndef HFT_RMIC_CONTRACT_SVH
`define HFT_RMIC_CONTRACT_SVH

// Frozen integration contract.
// HFT source: Eric99720/hft-full-system-fpga @
//   50217fad1fd580f8c451ba893f9035f4be1dc21a
// RMIC source: Eric99720/RMIC @
//   de6c300f4f18b18296f013287ab0eca70d3abb72
//
// These constants intentionally mirror the pinned upstream headers/packer and
// are checked by scripts/check_dependency_contracts.py when submodules exist.

`define HFT_RMIC_ORDER_WIDTH 256

`define HFT_RMIC_PRICE_LSB       0
`define HFT_RMIC_QTY_LSB         32
`define HFT_RMIC_SIDE_LSB        48
`define HFT_RMIC_TIF_LSB         56
`define HFT_RMIC_POS_EFFECT_LSB  64
`define HFT_RMIC_INV_FLAG_LSB    72
`define HFT_RMIC_INV_ACNO_LSB    80
`define HFT_RMIC_ORDER_ID_LSB    112
`define HFT_RMIC_ORDER_NO_LSB    144
`define HFT_RMIC_SYMBOL_SLOT_LSB 184
`define HFT_RMIC_FLAGS_LSB       200
`define HFT_RMIC_ORD_TYPE_LSB    208

// The frozen HFT packer stores only the low 16 quantity bits into order_data.
`define HFT_RMIC_PACKED_QTY_WIDTH 16

// Packed TMP-side byte generated by hft_order_data_packer.
`define HFT_RMIC_TMP_SIDE_BUY  8'h01
`define HFT_RMIC_TMP_SIDE_SELL 8'h02

// RMIC normalized side encoding from rmic_defs.svh.
`define HFT_RMIC_RMIC_SIDE_BUY  1'b0
`define HFT_RMIC_RMIC_SIDE_SELL 1'b1

`endif
