`timescale 1ns/1ps
// HFT_RMIC I5 integration-owned derivative.
// Provenance: deps/hft-full-system-fpga/rtl/top/hft_dual_xgmii_full_system_top.v
// pinned at 50217fad1fd580f8c451ba893f9035f4be1dc21a.
// Dual clocks, accepted market CDC and trading-port network ownership are
// retained; only the contained trading core is risk-aware.
`default_nettype none

module hft_rmic_dual_xgmii_full_system_top_v1 #(
    parameter integer MAX_FRAME_BYTES = 512,
    parameter integer DATA_WIDTH = 64,
    parameter integer KEEP_WIDTH = 8,
    parameter [47:0] LOCAL_MAC = 48'h020000000001,
    parameter [47:0] REMOTE_MAC = 48'h020000000002,
    parameter [31:0] LOCAL_IP = 32'h0a000001,
    parameter [31:0] REMOTE_IP = 32'h0a000002,
    parameter [15:0] UDP_MARKET_PORT = 16'd5500,
    parameter [15:0] TCP_LOCAL_PORT = 16'd9000,
    parameter [15:0] TCP_REMOTE_PORT = 16'd8000,
    parameter [31:0] LOCAL_INITIAL_SEQ = 32'h01020304,
    parameter [31:0] ARP_TIMEOUT_CYCLES = 32'd128,
    parameter [7:0]  ARP_MAX_RETRIES = 8'd2,
    parameter [31:0] ACK_PIGGYBACK_DEADLINE_CYCLES = 32'd8,
    parameter integer MARKET_CDC_FIFO_DEPTH = 64,
    parameter integer TMP_RATE_WINDOW_CYCLES = 156250000,
    parameter integer MAINTENANCE_CLOCK_HZ = 156250000,
    parameter integer R05_TIMEOUT_CYCLES = 781250000
) (
    input  wire                   market_rx_clk,
    input  wire                   market_rx_rst_n,
    input  wire [DATA_WIDTH-1:0]  market_xgmii_rxd,
    input  wire [KEEP_WIDTH-1:0]  market_xgmii_rxc,

    input  wire                   trading_clk,
    input  wire                   trading_rst_n,
    input  wire                   connection_enable,
    input  wire                   link_up,
    input  wire                   clear_arp_cache,
    input  wire                   user_disconnect,
    input  wire [DATA_WIDTH-1:0]  trading_xgmii_rxd,
    input  wire [KEEP_WIDTH-1:0]  trading_xgmii_rxc,
    output wire [DATA_WIDTH-1:0]  trading_xgmii_txd,
    output wire [KEEP_WIDTH-1:0]  trading_xgmii_txc,

    // HFT_RMIC host/recovery configuration at the full-system boundary.
    input  wire                   risk_integration_ready,
    input  wire                   risk_accounting_ready,
    input  wire                   risk_global_kill,
    input  wire                   risk_recovery_clear,
    input  wire [255:0]           risk_order_type_allow_mask,
    input  wire [255:0]           risk_tif_allow_mask,
    input  wire [255:0]           risk_position_effect_allow_mask,
    input  wire                   risk_account_cfg_we,
    input  wire [3:0]             risk_account_cfg_index,
    input  wire                   risk_account_cfg_valid,
    input  wire [31:0]            risk_account_cfg_key,
    input  wire [7:0]             risk_account_cfg_value,
    input  wire                   risk_product_cfg_we,
    input  wire [3:0]             risk_product_cfg_index,
    input  wire                   risk_product_cfg_valid,
    input  wire [15:0]            risk_product_cfg_key,
    input  wire [7:0]             risk_product_cfg_value,
    input  wire                   risk_state_cfg_valid,
    output wire                   risk_state_cfg_ready,
    input  wire [7:0]             risk_state_cfg_account_id,
    input  wire [7:0]             risk_state_cfg_product_id,
    input  wire                   risk_state_cfg_enabled,
    input  wire [63:0]            risk_state_cfg_margin_budget,
    input  wire [63:0]            risk_state_cfg_margin_per_contract,
    input  wire [15:0]            risk_state_cfg_long_position,
    input  wire [15:0]            risk_state_cfg_short_position,
    input  wire [15:0]            risk_state_cfg_pending_open_long,
    input  wire [15:0]            risk_state_cfg_pending_open_short,
    input  wire [15:0]            risk_state_cfg_reserved_close_long,
    input  wire [15:0]            risk_state_cfg_reserved_close_short,
    output wire                   risk_state_cfg_done,
    output wire                   risk_state_cfg_ok,
    output wire [7:0]             risk_state_cfg_reason_code,
    output wire                   risk_store_init_done,
    output wire [1:0]             risk_transaction_owner,
    output wire                   risk_recovery_required,
    output wire                   risk_reject_valid,
    output wire [31:0]            risk_reject_order_id,
    output wire [1:0]             risk_reject_reason_source,
    output wire [7:0]             risk_reject_reason_code,
    output wire                   risk_exec_result_valid,
    output wire                   risk_exec_result_ok,
    output wire [1:0]             risk_exec_result_reason_source,
    output wire [7:0]             risk_exec_result_reason_code,
    output wire [31:0]            risk_exec_result_order_id,
    output wire [15:0]            risk_exec_result_remaining_qty,
    output wire                   risk_exec_metadata_error,
    output wire                   risk_exec_queue_overflow,

    output wire                   tcp_connected,
    output wire                   network_ready,
    output wire                   order_tx_enable,
    output wire                   tx_ready,
    output wire                   app_tx_enable,
    output wire [3:0]             runtime_state,
    output wire [31:0]            tx_next_seq,
    output wire [31:0]            rx_next_ack,
    output wire [31:0]            app_tx_count,
    output wire [31:0]            syn_tx_count,
    output wire [31:0]            final_ack_tx_count,
    output wire [31:0]            pure_ack_tx_count,
    output wire [31:0]            runtime_error_count,
    output wire                   mandatory_ack_pending,
    output wire [31:0]            mandatory_ack_deadline_count,
    output wire [31:0]            ack_piggyback_count,
    output wire                   app_wire_active,
    output wire [47:0]            learned_remote_mac,
    output wire                   learned_remote_mac_valid,
    output wire                   round_session_ready,
    output wire [3:0]             round_session_state,
    output wire                   round_tmp_message_start_accept,
    output wire [7:0]             round_tmp_message_start_type,
    output wire                   round_flow_credit_available,
    output wire [15:0]            round_flow_message_count,
    output wire                   delivery_unknown,
    output wire [31:0]            delivery_unknown_count,
    output wire [31:0]            reconnect_count,
    output wire [15:0]            app_payload_len,
    output wire [31:0]            app_sent_count,
    output wire [31:0]            arp_request_count,
    output wire [31:0]            arp_reply_count,
    output wire [31:0]            arp_timeout_count,
    output wire [31:0]            arp_retry_count,
    output wire [31:0]            arbiter_arp_packet_count,
    output wire [31:0]            arbiter_app_packet_count,
    output wire [31:0]            app_builder_frame_seq_num,
    output wire [31:0]            app_builder_frame_ack_num,
    output wire [15:0]            app_builder_frame_payload_len,
    output wire                   trading_rx_frame_done,
    output wire                   trading_rx_frame_error,
    output wire                   xgmii_tx_frame_done,
    output wire                   xgmii_tx_frame_error,
    output wire [7:0]             xgmii_tx_error_code,
    output wire [2:0]             xgmii_tx_source_select,

    output wire                   market_rx_frame_done,
    output wire                   market_rx_frame_error,
    output wire                   market_rx_fcs_ok,
    output wire [7:0]             market_hot_error_code,
    output wire                   market_cdc_overflow_sticky,
    output wire                   market_cdc_src_reset_busy,
    output wire                   market_cdc_dst_reset_busy,
    output wire                   market_cdc_dst_record_valid,
    output wire [1:0]             market_cdc_dst_record_kind,
    output wire                   round_app_subsystem_ready,
    output wire                   round_selected_book_valid,
    output wire                   round_strategy_order_valid_seen,
    output wire                   round_encoder_order_accepted,
    output wire                   round_chip_error,
    output wire                   round_market_health_stale,
    output wire                   round_market_checksum_error_seen,
    output wire                   round_market_recovery_seen,
    output wire [DATA_WIDTH-1:0]  round_tx_data,
    output wire [KEEP_WIDTH-1:0]  round_tx_keep,
    output wire                   round_tx_valid,
    output wire                   round_tx_last,
    output wire [15:0]            round_tx_payload_len,
    output wire                   round_tx_complete
);

    wire market_axis_valid;
    wire [DATA_WIDTH-1:0] market_axis_data;
    wire [KEEP_WIDTH-1:0] market_axis_keep;
    wire market_axis_last;
    wire market_axis_user;
    wire [7:0] market_rx_error_code_unused;
    wire [15:0] market_rx_frame_len_unused;

    wire market_spec_valid;
    wire [DATA_WIDTH-1:0] market_spec_data;
    wire [KEEP_WIDTH-1:0] market_spec_keep;
    wire market_spec_last;
    wire market_commit;
    wire market_squash;

    wire trading_spec_valid;
    wire [DATA_WIDTH-1:0] trading_spec_data;
    wire [KEEP_WIDTH-1:0] trading_spec_keep;
    wire trading_spec_last;
    wire trading_commit;
    wire trading_squash;
    wire market_cdc_overflow_pulse_unused;
    wire market_cdc_underflow_sticky_unused;
    wire market_cdc_full_unused;
    wire market_cdc_src_accept_unused;

    hft_xgmii_rx_decoder #(
        .MAX_FRAME_BYTES(MAX_FRAME_BYTES),
        .DATA_WIDTH(DATA_WIDTH),
        .KEEP_WIDTH(KEEP_WIDTH),
        .FCS_BYPASS(1'b0),
        .EARLY_RESTART_ALWAYS_READY(1'b1)
    ) u_market_xgmii_rx (
        .clk(market_rx_clk),
        .rst_n(market_rx_rst_n),
        .xgmii_rxd(market_xgmii_rxd),
        .xgmii_rxc(market_xgmii_rxc),
        .m_axis_tvalid(market_axis_valid),
        .m_axis_tready(1'b1),
        .m_axis_tdata(market_axis_data),
        .m_axis_tkeep(market_axis_keep),
        .m_axis_tlast(market_axis_last),
        .m_axis_tuser(market_axis_user),
        .frame_done(market_rx_frame_done),
        .frame_error(market_rx_frame_error),
        .error_code(market_rx_error_code_unused),
        .frame_len(market_rx_frame_len_unused),
        .fcs_ok(market_rx_fcs_ok)
    );

    hft_market_rx_hot_path #(
        .DATA_WIDTH(DATA_WIDTH),
        .KEEP_WIDTH(KEEP_WIDTH),
        .LOCAL_MAC(LOCAL_MAC),
        .LOCAL_IP(LOCAL_IP),
        .UDP_MARKET_PORT(UDP_MARKET_PORT)
    ) u_market_hot_path (
        .clk(market_rx_clk),
        .rst_n(market_rx_rst_n),
        .tap_valid(market_axis_valid),
        .tap_data(market_axis_data),
        .tap_keep(market_axis_keep),
        .tap_last(market_axis_last),
        .tap_user(market_axis_user),
        .spec_valid(market_spec_valid),
        .spec_data(market_spec_data),
        .spec_keep(market_spec_keep),
        .spec_last(market_spec_last),
        .commit_valid(market_commit),
        .squash_valid(market_squash),
        .error_code(market_hot_error_code)
    );

    hft_market_transaction_cdc #(
        .DATA_WIDTH(DATA_WIDTH),
        .KEEP_WIDTH(KEEP_WIDTH),
        .FIFO_DEPTH(MARKET_CDC_FIFO_DEPTH)
    ) u_market_transaction_cdc (
        .src_clk(market_rx_clk),
        .src_rst_n(market_rx_rst_n),
        .src_spec_valid(market_spec_valid),
        .src_spec_data(market_spec_data),
        .src_spec_keep(market_spec_keep),
        .src_spec_last(market_spec_last),
        .src_commit(market_commit),
        .src_squash(market_squash),
        .dst_clk(trading_clk),
        .dst_rst_n(trading_rst_n),
        .dst_spec_valid(trading_spec_valid),
        .dst_spec_data(trading_spec_data),
        .dst_spec_keep(trading_spec_keep),
        .dst_spec_last(trading_spec_last),
        .dst_commit(trading_commit),
        .dst_squash(trading_squash),
        .src_overflow_pulse(market_cdc_overflow_pulse_unused),
        .src_overflow_sticky(market_cdc_overflow_sticky),
        .dst_underflow_sticky(market_cdc_underflow_sticky_unused),
        .src_fifo_full(market_cdc_full_unused),
        .src_fifo_reset_busy(market_cdc_src_reset_busy),
        .dst_fifo_reset_busy(market_cdc_dst_reset_busy),
        .src_record_accept(market_cdc_src_accept_unused),
        .dst_record_valid(market_cdc_dst_record_valid),
        .dst_record_kind(market_cdc_dst_record_kind)
    );

    hft_rmic_xgmii_network_layer_e2e_top_v1 #(
        .MAX_FRAME_BYTES(MAX_FRAME_BYTES),
        .MAX_PAYLOAD_BYTES(256),
        .DATA_WIDTH(DATA_WIDTH),
        .KEEP_WIDTH(KEEP_WIDTH),
        .LOCAL_MAC(LOCAL_MAC),
        .REMOTE_MAC(REMOTE_MAC),
        .LOCAL_IP(LOCAL_IP),
        .REMOTE_IP(REMOTE_IP),
        .UDP_MARKET_PORT(UDP_MARKET_PORT),
        .TCP_LOCAL_PORT(TCP_LOCAL_PORT),
        .TCP_REMOTE_PORT(TCP_REMOTE_PORT),
        .LOCAL_INITIAL_SEQ(LOCAL_INITIAL_SEQ),
        .ARP_TIMEOUT_CYCLES(ARP_TIMEOUT_CYCLES),
        .ARP_MAX_RETRIES(ARP_MAX_RETRIES),
        .ACK_PIGGYBACK_DEADLINE_CYCLES(ACK_PIGGYBACK_DEADLINE_CYCLES),
        .ENABLE_R01_TX_STREAM(1'b1),
        .ENABLE_EXTERNAL_MARKET_TRANSACTION(1'b1),
        .ENABLE_TMP_MAINTENANCE(1'b1),
        .ENABLE_TMP_FLOW_CONTROL(1'b1),
        .ENABLE_HEARTBEAT_PLACEHOLDER(1'b0),
        .TMP_RATE_WINDOW_CYCLES(TMP_RATE_WINDOW_CYCLES),
        .MAINTENANCE_CLOCK_HZ(MAINTENANCE_CLOCK_HZ),
        .R05_TIMEOUT_CYCLES(R05_TIMEOUT_CYCLES)
    ) u_trading_core (
        .clk(trading_clk),
        .rst_n(trading_rst_n),
        .connection_enable(connection_enable),
        .link_up(link_up),
        .clear_arp_cache(clear_arp_cache),
        .heartbeat_trigger(1'b0),
        .user_disconnect(user_disconnect),
        .xgmii_rxd(trading_xgmii_rxd),
        .xgmii_rxc(trading_xgmii_rxc),
        .xgmii_txd(trading_xgmii_txd),
        .xgmii_txc(trading_xgmii_txc),
        .external_market_valid(trading_spec_valid),
        .external_market_data(trading_spec_data),
        .external_market_keep(trading_spec_keep),
        .external_market_last(trading_spec_last),
        .external_market_commit(trading_commit),
        .external_market_squash(trading_squash),
        .risk_integration_ready(risk_integration_ready),
        .risk_accounting_ready(risk_accounting_ready),
        .risk_global_kill(risk_global_kill),
        .risk_recovery_clear(risk_recovery_clear),
        .risk_order_type_allow_mask(risk_order_type_allow_mask),
        .risk_tif_allow_mask(risk_tif_allow_mask),
        .risk_position_effect_allow_mask(risk_position_effect_allow_mask),
        .risk_account_cfg_we(risk_account_cfg_we),
        .risk_account_cfg_index(risk_account_cfg_index),
        .risk_account_cfg_valid(risk_account_cfg_valid),
        .risk_account_cfg_key(risk_account_cfg_key),
        .risk_account_cfg_value(risk_account_cfg_value),
        .risk_product_cfg_we(risk_product_cfg_we),
        .risk_product_cfg_index(risk_product_cfg_index),
        .risk_product_cfg_valid(risk_product_cfg_valid),
        .risk_product_cfg_key(risk_product_cfg_key),
        .risk_product_cfg_value(risk_product_cfg_value),
        .risk_state_cfg_valid(risk_state_cfg_valid),
        .risk_state_cfg_ready(risk_state_cfg_ready),
        .risk_state_cfg_account_id(risk_state_cfg_account_id),
        .risk_state_cfg_product_id(risk_state_cfg_product_id),
        .risk_state_cfg_enabled(risk_state_cfg_enabled),
        .risk_state_cfg_margin_budget(risk_state_cfg_margin_budget),
        .risk_state_cfg_margin_per_contract(risk_state_cfg_margin_per_contract),
        .risk_state_cfg_long_position(risk_state_cfg_long_position),
        .risk_state_cfg_short_position(risk_state_cfg_short_position),
        .risk_state_cfg_pending_open_long(risk_state_cfg_pending_open_long),
        .risk_state_cfg_pending_open_short(risk_state_cfg_pending_open_short),
        .risk_state_cfg_reserved_close_long(risk_state_cfg_reserved_close_long),
        .risk_state_cfg_reserved_close_short(risk_state_cfg_reserved_close_short),
        .risk_state_cfg_done(risk_state_cfg_done),
        .risk_state_cfg_ok(risk_state_cfg_ok),
        .risk_state_cfg_reason_code(risk_state_cfg_reason_code),
        .risk_store_init_done(risk_store_init_done),
        .risk_transaction_owner(risk_transaction_owner),
        .risk_recovery_required(risk_recovery_required),
        .risk_reject_valid(risk_reject_valid),
        .risk_reject_order_id(risk_reject_order_id),
        .risk_reject_reason_source(risk_reject_reason_source),
        .risk_reject_reason_code(risk_reject_reason_code),
        .risk_exec_result_valid(risk_exec_result_valid),
        .risk_exec_result_ok(risk_exec_result_ok),
        .risk_exec_result_reason_source(risk_exec_result_reason_source),
        .risk_exec_result_reason_code(risk_exec_result_reason_code),
        .risk_exec_result_order_id(risk_exec_result_order_id),
        .risk_exec_result_remaining_qty(risk_exec_result_remaining_qty),
        .risk_exec_metadata_error(risk_exec_metadata_error),
        .risk_exec_queue_overflow(risk_exec_queue_overflow),
        .tcp_connected(tcp_connected),
        .network_ready(network_ready),
        .order_tx_enable(order_tx_enable),
        .tx_ready(tx_ready),
        .app_tx_enable(app_tx_enable),
        .runtime_state(runtime_state),
        .tx_next_seq(tx_next_seq),
        .rx_next_ack(rx_next_ack),
        .app_tx_count(app_tx_count),
        .syn_tx_count(syn_tx_count),
        .final_ack_tx_count(final_ack_tx_count),
        .pure_ack_tx_count(pure_ack_tx_count),
        .runtime_error_count(runtime_error_count),
        .arp_remote_mac_valid(learned_remote_mac_valid),
        .arp_remote_mac(learned_remote_mac),
        .mandatory_ack_pending(mandatory_ack_pending),
        .mandatory_ack_deadline_count(mandatory_ack_deadline_count),
        .ack_piggyback_count(ack_piggyback_count),
        .app_wire_active(app_wire_active),
        .delivery_unknown(delivery_unknown),
        .delivery_unknown_count(delivery_unknown_count),
        .app_payload_len(app_payload_len),
        .app_sent_count(app_sent_count),
        .arp_request_count(arp_request_count),
        .arp_reply_count(arp_reply_count),
        .arp_timeout_count(arp_timeout_count),
        .arp_retry_count(arp_retry_count),
        .arbiter_arp_packet_count(arbiter_arp_packet_count),
        .arbiter_app_packet_count(arbiter_app_packet_count),
        .app_builder_frame_seq_num(app_builder_frame_seq_num),
        .app_builder_frame_ack_num(app_builder_frame_ack_num),
        .app_builder_frame_payload_len(app_builder_frame_payload_len),
        .xgmii_rx_frame_done(trading_rx_frame_done),
        .xgmii_rx_frame_error(trading_rx_frame_error),
        .reconnect_count(reconnect_count),
        .round_session_ready(round_session_ready),
        .round_session_state(round_session_state),
        .round_tmp_message_start_accept(round_tmp_message_start_accept),
        .round_tmp_message_start_type(round_tmp_message_start_type),
        .round_flow_credit_available(round_flow_credit_available),
        .round_flow_message_count(round_flow_message_count),
        .round_app_subsystem_ready(round_app_subsystem_ready),
        .round_selected_book_valid(round_selected_book_valid),
        .round_strategy_order_valid_seen(round_strategy_order_valid_seen),
        .round_encoder_order_accepted(round_encoder_order_accepted),
        .round_chip_error(round_chip_error),
        .round_market_health_stale(round_market_health_stale),
        .round_market_checksum_error_seen(round_market_checksum_error_seen),
        .round_market_recovery_seen(round_market_recovery_seen),
        .round_tx_data(round_tx_data),
        .round_tx_keep(round_tx_keep),
        .round_tx_valid(round_tx_valid),
        .round_tx_last(round_tx_last),
        .round_tx_payload_len(round_tx_payload_len),
        .round_tx_complete(round_tx_complete),
        .xgmii_tx_frame_done(xgmii_tx_frame_done),
        .xgmii_tx_frame_error(xgmii_tx_frame_error),
        .xgmii_tx_error_code(xgmii_tx_error_code),
        .xgmii_tx_source_select(xgmii_tx_source_select)
    );

endmodule

`default_nettype wire
