#!/usr/bin/env python3
"""Synchronize generated project-state blocks in root project records."""
from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
STATE_PATH = ROOT / "docs" / "project_state.json"
BEGIN = "<!-- project-state:begin -->"
END = "<!-- project-state:end -->"


def load_state() -> dict:
    with STATE_PATH.open("r", encoding="utf-8") as f:
        return json.load(f)


def summary_block(s: dict) -> str:
    p = s["phase"]
    return "\n".join([
        BEGIN,
        "<!-- Generated by scripts/sync_project_records.py; edit docs/project_state.json. -->",
        f"Record revision: `{s['record_revision']}`.",
        "",
        f"**{p['id']} / {p['status']}** — {s['handoff']}",
        "",
        f"Status observed: `{s['observed_at_utc']}`; this is a recorded handoff, not live telemetry.",
        "",
        f"Goal: {s['goal']}",
        "",
        f"Next: {s['next_action']}",
        "",
        f"[Active plan]({s['active_plan']}) · [Task board](TASKS.md) · [Progress](PROGRESS.md).",
        END,
    ])


def tasks_block(s: dict) -> str:
    lines = [
        BEGIN,
        "<!-- Generated by scripts/sync_project_records.py; edit docs/project_state.json. -->",
        f"Record revision: `{s['record_revision']}`.",
        "",
        "| ID | Status | Task | Acceptance |",
        "| --- | --- | --- | --- |",
    ]
    for task in s["tasks"]:
        acceptance = task["acceptance"].replace("|", "\\|")
        title = task["title"].replace("|", "\\|")
        lines.append(f"| `{task['id']}` | **{task['status']}** | {title} | {acceptance} |")
    lines += ["", END]
    return "\n".join(lines)


def progress_block(s: dict) -> str:
    lines = [
        BEGIN,
        "<!-- Generated by scripts/sync_project_records.py; edit docs/project_state.json. -->",
        f"Record revision: `{s['record_revision']}`.",
        "",
    ]
    for m in s["milestones"]:
        lines.append(f"- {m['date']} — **{m['id']}**: {m['summary']} ([evidence]({m['evidence']}))")
    lines += ["", END]
    return "\n".join(lines)


def changelog_block(s: dict) -> str:
    lines = [
        BEGIN,
        "<!-- Generated by scripts/sync_project_records.py; edit docs/project_state.json. -->",
        f"Record revision: `{s['record_revision']}`.",
        "",
    ]
    for m in reversed(s["milestones"][-8:]):
        lines.append(f"- **{m['date']} / {m['id']}** — {m['summary']}")
    lines += ["", END]
    return "\n".join(lines)


def replace_block(text: str, block: str) -> str:
    if BEGIN not in text or END not in text:
        raise RuntimeError("missing project-state markers")
    start = text.index(BEGIN)
    end = text.index(END, start) + len(END)
    return text[:start] + block + text[end:]


def expected_files(s: dict) -> dict[Path, str]:
    renders = {
        ROOT / "README.md": summary_block(s),
        ROOT / "CURRENT_PHASE.md": summary_block(s),
        ROOT / "TASKS.md": tasks_block(s),
        ROOT / "PROGRESS.md": progress_block(s),
        ROOT / "CHANGELOG.md": changelog_block(s),
    }
    out: dict[Path, str] = {}
    for path, block in renders.items():
        current = path.read_text(encoding="utf-8")
        out[path] = replace_block(current, block)
    return out


def main() -> int:
    parser = argparse.ArgumentParser()
    g = parser.add_mutually_exclusive_group(required=True)
    g.add_argument("--write", action="store_true")
    g.add_argument("--check", action="store_true")
    args = parser.parse_args()

    state = load_state()
    expected = expected_files(state)
    stale: list[str] = []
    for path, content in expected.items():
        current = path.read_text(encoding="utf-8")
        if current != content:
            stale.append(str(path.relative_to(ROOT)))
            if args.write:
                path.write_text(content, encoding="utf-8", newline="\n")

    if args.check and stale:
        print("PROJECT_RECORD_SYNC_FAIL")
        for p in stale:
            print(f"stale={p}")
        return 1

    if args.write:
        print("PROJECT_RECORD_SYNC_WRITE_PASS")
    else:
        print("PROJECT_RECORD_SYNC_CHECK_PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
